zofe/rapyd-laravel

src/lang/es/rapyd.php
Hi I'd like to share this file.
=> Spanish Translation of rapyd-laravel

src/DataSet.php, src/Url.php, views/datagrid.blade.php
See https://github.com/zofe/rapyd-laravel/issues/153#issuecomment-112147703
=> Escape pagination and order by links

src/DataForm/Field/Field.php, src/DataForm/Field/Number.php, src/DataForm/Field/NumberRage.php
Number field will automatic trigger the form validation on supported browsers , 
and will automatic change keyboard to "number keyboard" on mobile device when filling forms (it's very convenient)
Numberrange is the range query for number type
=> Add new fields: Number & Numberrange

lang/fr/rapyd.php
There is the french translation file for this plugin
=> french translation

src/DataForm/Field/Field.php
+ Laravel will explode rules to array
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Validation/Validator.php#L212
+ Support regex pattern with pipe character
http://laravel.com/docs/5.1/validation#rule-regex
=> save field rules to array 

src/DataForm/Field/Colorpicker.php, src/DataForm/Field/Field.php, src/DataForm/Field/Image.php, src/DataForm/Field/Number.php
=> bugfix:rule() upward compatible

src/DataForm/Field/Field.php
+ Usage as same as [Laravel Validation unique rule](http://laravel.com/docs/5.1/validation#rule-unique)
+ Auto except current model
=> add unique function to Field

lang/zh-CN/rapyd.php
=> improve chinese translate

src/DataForm/Field/Autocomplete.php, src/DataForm/Field/Field.php
Hello i have improved some little bugs
=> Small bugs fix

src/DataForm/Field/Multiselect.php
You can't use iluminate form in laravel 5.2
=> Bug into this file

src/DataForm/DataForm.php
Class is not reconigzed in show mode, i fixed it
=> Classes on show mode

lang/zh-CN/rapyd.php
=> improve chinese translate for v2.2.x

lang/nl/rapyd.php
Added first version of dutch translartions
=> dutch translation files

lang/pt/rapyd.php
Hey,
I have added the no_records key to the PT language messages that's missing.
Thanks,
Jonata Weber
=> Add no_records key message to the PT language

views/dataform/field.blade.php
=> Added star in required not-inline fields too

src/DataForm/Field/Field.php
Example: 
```php
$edit->add('type_video_player_code','Player code','textarea')->withXssFilter(false);
```
=> Add a method to set auto apply xss filter or not

src/DataGrid/DataGrid.php
Signed-off-by: Jose Pacheco <jpacheco@csatf.org>
=> Fixes #383, Typo

lang/fr/rapyd.php
Several changes in the french wording.
=> French translations fixed

src/Widget.php, views/dataform.blade.php, views/toolbar.blade.php
Adds the BC in addition to BR and BL options to center the form buttons
=> Option to center form buttons

views/datagrid.blade.php
.table-responsive added to .rpd-datagrid
=> #380 Responsive DataGrid

lang/id/rapyd.php
Please update this on rapyd, because it is need for our ops team. thank you.
=> update language for Indonesia

src/DataSet.php
Resolve #424.
Added a little section to DataSet::build() to allow it to deal with PDOStatement as a source.
This is particularly helpful went a huge number of rows cannot be fetch in it entirety in an array.
2 caveats:
1) PDOStatements often do not have the ability to return the total amount of rows since not all have been fetched yet. This is forcing us to use a paginator that will not show individual pages.
2) The column ordering must be handled by the code that provides the source/PDOStatement as all rows will not be loaded and therefore cannot be sorted.
Let me know what you think.
Cheers.
/s
=> Added ability to specify a PDOStatement as a data source.

views/datagrid/actions.blade.php
Please, merge this commit. I have to customize that buttons but can't do it correctly without css classes. Thank :-)
=> Added classes for actions

src/DataForm/Field/Field.php, src/DataSet.php
=> PHP 7.3 compatibility fix: "continue" in switch

src/DataForm/Field/Tags.php
same as ajax controller response
=> fix Bloodhound show 10 suggestions

composer.json, src/Controllers/AjaxController.php, src/DataForm/DataForm.php, src/DataForm/Field/Autocomplete.php, src/DataForm/Field/Checkbox.php, src/DataForm/Field/Field.php, src/DataForm/Field/File.php, src/DataForm/Field/Image.php, src/DataForm/Field/Map.php, src/DataTree/DataTree.php, src/Demo/DemoController.php, src/Rapyd.php
This pull request depends on: https://github.com/zofe/burp/pull/3
=> Add support for laravel 6
